apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: services
spec:
  serviceAccountName: services-sa
  path: ./archive/staging
  targetNamespace: services
