apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-team
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/warrenwb/apps
  ref:
    branch: refactoring-folder-structure
  targetNamespace: apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-team
  namespace: flux-system
spec:
  serviceAccountName: dev-team
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dev-team
  path: ./podinfo-one
  prune: true
  targetNamespace: apps