---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/warrenwb/apps
