apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-team
  namespace: apps
spec:
  interval: 1m
  url: https://github.com/warrenwb/apps
  ref:
    branch: refactoring-folder-structure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-team
  namespace: apps
spec:
  serviceAccountName: dev-team
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dev-team
    path: ./archive
  prune: true

# ...
# spec:
#   sourceRef:
#     kind: GitRepository
#     name: dev-team
#   path: "./kustomize" => this will be added by the .staging or .productiomn oiverlYS
#   prune: true


