apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elasticsearch-templates
  namespace: flux-system
spec:
  serviceAccountName: elasticsearch-templates-sa
  path: ./elasticsearch-templates/tenants/staging
  targetNamespace: elasticsearch-templates
