apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: services-gitrepo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/warrenwb/apps
  ref:
    branch: refactoring-folder-structure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  serviceAccountName: services-sa
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: services-gitrepo
  path: ./archive
  prune: true
  targetNamespace: services