apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  serviceAccountName: kustomize-controller
  path: ./elasticsearch/staging
