---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-phenix-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: phenix-operator-system-sa
  namespace: elastic-phenix-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: phenix-reconciler
  namespace: elastic-phenix-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:phenix:reconciler
- kind: ServiceAccount
  name: phenix-operator-system-sa
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: elasticsearch-operators
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/warrenwb/apps
  ref:
    branch: refactoring-folder-structure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: phenix-operator-crds
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  serviceAccountName: kustomize-controller
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: elasticsearch-operators
  path: ./elasticsearch/operators/phenix-operator
  prune: true
  targetNamespace: elastic-phenix-operator-system