apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-team
  namespace: flux-system
spec:
  serviceAccountName: dev-team
  path: ./archive/staging
  targetNamespace: apps
