apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch-helmrelease
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  releaseName: elasticsearch-release
  chart:
    spec:
      version: ">=1.0.0-alpha"
  values:
    replicaCount: 1
    image:
      repository: nginx
      pullPolicy: IfNotPresent
  # targetNamespace: elasticsearch