---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  interval: 1m0s
  path: ./elasticsearch
  prune: false
  serviceAccountName: elasticsearch
  sourceRef:
    kind: GitRepository
    name: elasticsearch
