---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: elasticsearch-templates
  name: elasticsearch-templates
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: elasticsearch-templates
  name: elasticsearch-templates-sa
  namespace: elasticsearch-templates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reconciler-elasticsearch-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kustomize-controller
  namespace: flux-system
- kind: ServiceAccount
  name: helm-controller
  namespace: flux-system
- kind: ServiceAccount
  name: elasticsearch-templates-sa
  namespace: elasticsearch-templates
- kind: ServiceAccount
  name: phenix-operator-system-sa
  namespace: elastic-phenix-operator-system
- kind: User
  name: gotk:elasticsearch-templates:reconciler
  namespace: elasticsearch-templates