---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: elasticsearch-templates
  name: elasticsearch-templates
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: elasticsearch-templates
  name: elasticsearch-templates-sa
  namespace: elasticsearch-templates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: elasticsearch-templates
  name: es-templates-clusterbinding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: ""
  kind: User
  name: gotk:elasticsearch-templates:reconciler
- kind: ServiceAccount
  name: es-templates-sa
- kind: ServiceAccount
  name: phenix-operator-system-sa
  namespace: elastic-phenix-operator-system